const tags = [
   'accesorios para vehículos',
   'agro',
   'alimentos y bebidas',
   'animales y mascotas',
   'antigüedades y colecciones',
   'arte, papelería y mercería',
   'bebés',
   'belleza y cuidado personal',
   'boletas para espectáculos',
   'cámaras y accesorios',
   'carros, motos y otros',
   'celulares y teléfonos',
   'computación',
   'consolas y videojuegos',
   'deportes y fitness',
   'electrodomésticos',
   'electrónica, audio y video',
   'herramientas y construcción',
   'hogar y muebles',
   'industrias y oficinas',
   'inmuebles',
   'instrumentos musicales',
   'juegos y juguetes',
   'libros, revistas y comics',
   'música, películas y series',
   'recuerdos, piñatería y fiestas',
   'relojes y joyas',
   'ropa y accesorios',
   'salud y equipamiento médico',
   'servicios'
];

export default tags;
